{{- template "common.hook" . -}}
---
{{- template "common.microservice" (dict "context" . "microservice" (merge .Values.arquive .Values.microservicecommon)) -}}
---
{{- template "common.microservice" (dict "context" . "microservice" (merge .Values.core .Values.microservicecommon)) -}}
---
{{- template "common.client" (dict "context" . "client" .Values.client "gateway" .Values.gateway) -}}
---
{{- template "common.gateway" (dict "context" . "gateway" (merge .Values.gateway .Values.microservicecommon)) -}}
---
# Deployment below is required to fix the nginx redirect issue in the application.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.module.fullname" (dict "context" . "module" .Values.client) }}
data:
  default.conf: |
    server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;
    root /usr/share/nginx/html;
    index index.html index.htm;
    server_name localhost;
    location / {
        try_files $uri $uri/ =404;
    }
    location /api {
        proxy_pass      http://{{ include "common.module.fullname" (dict "context" . "module" .Values.gateway) }}:8080/api;
        include         /etc/nginx/proxy.conf;
    }
    location /cas/logout {
        proxy_pass      http://{{ include "common.module.fullname" (dict "context" . "module" .Values.gateway) }}:8080/cas/logout;
        include         /etc/nginx/proxy.conf;
    }
    location /login/cas {
        proxy_pass      http://{{ include "common.module.fullname" (dict "context" . "module" .Values.gateway) }}:8080/login/cas;
        include         /etc/nginx/proxy.conf;
    }
    location /core {
        proxy_pass      http://{{ include "common.module.fullname" (dict "context" . "module" .Values.gateway) }}:8080/core;
        include         /etc/nginx/proxy.conf;
    }
    location /arquivo {
        proxy_pass      http://{{ include "common.module.fullname" (dict "context" . "module" .Values.gateway) }}:8080/arquivo;
        include         /etc/nginx/proxy.conf;
    }
    location /login {
        rewrite ^/* / permanent;
    }
    }
  proxy.conf: |-
    proxy_http_version      1.1;
    proxy_redirect          off;
    proxy_set_header        Host            $host;
    proxy_set_header        X-Real-IP       $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    client_max_body_size    1000M;
    client_body_buffer_size 128k;
    proxy_connect_timeout   180;
    proxy_send_timeout      180;
    proxy_read_timeout      180;
    proxy_buffer_size       128k;
    proxy_buffers           4 256k;
    proxy_busy_buffers_size 256k;
