{{- define "common.microservice.hpa" -}}
{{- $context := .context }}
{{- $microservice := merge .microservice $context.Values.common.deployment $context.Values.common.microservice }}
{{- $module := dict "context" $context "module" $microservice }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "common.module.fullname" $module }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "common.module.fullname" $module }}
  minReplicas: {{ $microservice.hpa.minReplicas }}
  maxReplicas: {{ $microservice.hpa.maxReplicas }}
  metrics:
  {{- toYaml $microservice.hpa.metrics | nindent 2}}
{{- end -}}
